version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nilerr
    - staticcheck
    - unconvert
    - unused
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - nilerr
          - staticcheck
          - unused
        path: _test\.go
