linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  govet:
    check-shadowing: false
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - goconst
    - gochecknoglobals
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint
        - staticcheck
        - scopelint
        - gochecknoglobals
        - noctx
        - unparam

allow-parallel-runners: true
