env:
  - GITHUB_TOKEN={{ if index .Env "GITHUB_TOKEN" }}{{ .Env.GITHUB_TOKEN }}{{else}}''{{end}}
archives:
  - format: binary
    name_template: "shipyard-{{ .Os }}-{{ .Arch }}"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary:
      shipyard-{{.Os}}-{{.Arch}}
    ldflags:
      - -s -w
      - -X shipyard/version.GitCommit={{.Version}}
      - -X shipyard/version.Version={{.ShortCommit}}
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
brews:
  -
    name: shipyard
    tap:
      owner: shipyard
      name: homebrew-tap
      branch: main

    url_template: "https://github.com/shipyard/shipyard-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: shipyard
      email: hello@shipyard.build

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula

    homepage: "https://shipyard.build"
    description: "A tool to manage Ephemeral Environments on the Shipyard platform"
    license: "Apache2"

    install: |
      bin.install "shipyard-{{.Os}}-{{.Arch}}" => "shipyard"
