version: 2

env:
  - GITHUB_TOKEN={{ if index .Env "GITHUB_TOKEN" }}{{ .Env.GITHUB_TOKEN }}{{else}}''{{end}}

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: shipyard-{{.Os}}-{{.Arch}}
    ldflags:
      - -s -w
      - -X github.com/shipyard/shipyard-cli/version.GitCommit={{.ShortCommit}}
      - -X github.com/shipyard/shipyard-cli/version.Version={{.Version}}
archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  disable: true
homebrew_casks:
  - name: shipyard
    repository:
      owner: shipyard
      name: homebrew-tap
      branch: main

    commit_author:
      name: shipyard
      email: hello@shipyard.build

    commit_msg_template: "Cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks

    homepage: "https://shipyard.build"
    description: "A tool to manage Ephemeral Environments on the Shipyard platform"
    license: "Apache-2.0"
